export const permissionContants = {
    //Users
    READ_USERS: "READ_USERS",


    //Roles
    READ_ROLES: "READ_ROLES",
    ADD_ROLES: "ADD_ROLES",
    MODIFY_ROLES: "MODIFY_ROLES",
    DELETE_ROLES: "DELETE_ROLES",
    ASSIGN_ROLES_TO_USERS: "ASSIGN_ROLES_TO_USERS",
    UNASSIGN_ROLES_FROM_USERS: "UNASSIGN_ROLES_FROM_USERS"
}